### ISSUE TITLE
Sun avoidance not respected by pre-observation tuning

### ISSUE THREAD

**Issue by ktcrowley** [simonsobs/scheduler#37]
It appears the scheduler successfully accounts for sun avoidance when `policy.apply` is run -- that is, the scheduler will not begin an  observation until the sun is further away than the `sun-avoidance` angular distance in `rules` -- and it will start it ASAP after that point.

However, at least in SAT cases, the support for tuning readout channels seems to be to move to the initial starting az of the observation at a time before the obs start time, with the magnitude of the delay set by arg `det_setup` in `time_costs`. This clearly violates the purpose of sun avoidance, and currently for SATp1 the `det_setup` time cost is 40 mins, which is enough to not only violate the theta=45 sun avoidance criterion, but also the theta=41 shade criterion to protect the PE window on the SAT.

I would propose that the default behavior should be to shift the start time of the scan to a time `det_setup` later than the ideal (i.e. shift it to the future to allow space to get dets setup), and make the start time of the detector setup the first sun-safe time.

**Comment by kmharrington** [comment]
If we're relying on sun avoidance through the scheduler. Be very aware of the much larger issue: https://github.com/simonsobs/scheduler/issues/18 It only looks at azimuth / users 1D angles.

**Comment by ktcrowley** [comment]
I could be interested in trying to fix that issue at least, let me see if I can make headway there. It seems like proper wait times to include sun avoidance may be second order.

For other folks interested, I think most of us have been checking by hand that 2D sun avoidance is satisfied during daytime scans. It's probably not been perfect, though.
