### ISSUE TITLE
Make wait_until statements from scan blocks inherit times from scan_start

### ISSUE THREAD

**Issue by ktcrowley** [simonsobs/scheduler#41]
In trying to find appropriate ways to build in delays for CHWP behavior, some SATp1 schedulers (including myself) have been modifying variables output by this repo by hand. This has led to recognition of issues like #38 (that we may be screwing up target pointing by editing the `scan_start` variable) and a potentially bigger issue of not letting the CHWP spin up before scanning/data acquisition starts.

In a very minor issue we've identified, it's been hard to assess which variables control which actions, specifically around `scan_start`. Editing this variable only affects the pointing of the telescope at the start of the scan, and not the `wait_until` command further down. Editing this variable by hand is not ideal, but doing so once the schedule has been generated would be intuitive, and we could solve the issue of moving before CHWP spinup if we set the argument to `wait_until` to be the ISO timestamp from the datetime object `scan_start`.

**Comment by kmharrington** [comment]
I think this has totally been superseded by the state update, the sun safety setup, and the fact that we're basically just always running the HWP. 

Kevin please re-open this with more information of current issues if I'm wrong.
