### ISSUE TITLE
update preamble with hwp settings

### ISSUE THREAD

**Issue by guanyilun** [simonsobs/scheduler#52]
with this `sorunlib` hwp PR merged (https://github.com/simonsobs/sorunlib/pull/138), it means the preamble should probably be cleaned up with this.

**Comment by BrianJKoopman** [comment]
Yeah, that'd be great. I don't think the agent side of things is completely ready on satp1 yet though. @jlashner should comment when we can finally drop the HWP functions in the preamble.
