### ISSUE TITLE
Azimuth inconsistency between acu.move_to() and tag

### ISSUE THREAD

**Issue by yoshinori-0778** [simonsobs/scheduler#69]
We found generated schedule has Azimuth inconsistency between acu.move_to(az=-89.108, el=60.0) and tag='271-311'.
We noticed when we faced "ProgramTrack_position_failure" because ACU limits for the SATP are -90 to 450 degrees.

```
run.acu.move_to(az=-89.108, el=60.0)
run.wait_until('2024-06-02T01:28:12+00:00')
# hwp disabled
scan_stop = datetime.datetime(2024, 6, 2, 2, 28, tzinfo=datetime.timezone.utc)
if datetime.datetime.now(tz=UTC) < scan_stop - datetime.timedelta(minutes=10):
    run.seq.scan(
        description='NW. First choice',
        stop_time='2024-06-02T02:28:00+00:00',
        width=40.0, az_drift=0,
        subtype='cmb', tag='271-311',
    )
    run.smurf.bias_step(concurrent=True)
```

Used scripts:
- Script https://github.com/simonsobs/scheduler-scripts/tree/main/satp3/TSATScheduler.py

Used version:
- scheduler-scripts: commit d12e45ca2c83ced5ae0716e8f89ec4c8b7cb983e
- scheduler: commit 026bfc77498c598b8c02e15cc314b15a29332336

**Comment by ykyohei** [comment]
I guess we can solve this by changing az_limits? Recently satp1 policy changed this value from [-90, 450] to [-45, 405]
https://github.com/simonsobs/scheduler/blob/026bfc77498c598b8c02e15cc314b15a29332336/src/schedlib/policies/satp1.py#L234

**Comment by ykyohei** [comment]
I think we don't have this issue after changing az_limits
