### ISSUE TITLE
Geometries seem too hardcoded

### ISSUE THREAD

**Issue by skhrg** [simonsobs/scheduler#71]
Right now the way the UFM center's and radii are specified (ie: https://github.com/simonsobs/scheduler/blob/026bfc77498c598b8c02e15cc314b15a29332336/src/schedlib/policies/satp1.py#L16) seems a bit too hardcoded and "code as config" too me.

I know these values don't change very often but I think it would be cleaner to either take in a `geometries.yaml` or get these values directly from the output of `finalize_focal_plane`. If we do the former I can have `finalize_focal_plane` output the yaml file by default. Either change would be easy to do and also would reduce the need for each telescope to have its own `make_geometry` function.

**Comment by kmharrington** [comment]
I agree a config file would work equally well going into a make_geometry argument and is probably better long-term. In a "it's not broken while the sun avoidance issues are actually broken" world, I don't think this is be a high priority issue.

**Comment by mhasself** [comment]
I propose we close this as wontfix.  I don't think we benefit by tying this code too tightly to pipeline outputs or configs.  Code as config is inevitable here, as there are so many differences between platforms (from layouts, to schedule syntax, to actual algorithms and stuff).

**Comment by guanyilun** [comment]
closing as of now
