### ISSUE TITLE
"scans" of Saturn that start at 2.4 deg elevation

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/scheduler#8]
On the E2E system we keep getting Saturn scans generated that have the ACU move to an elevation of 2.4 deg elevation. This isn't realistic and also causes the ACU emulator to throw an error that stops all execution in the system.

**Comment by guanyilun** [comment]
this is a server configuration issue in scheduler-server. I think it's fixed.

**Comment by guanyilun** [comment]
I think so. I've rebuilt the docker image and launched it on E2E. Let me know if it's still happening.
